### ISSUE TITLE
[BE] 회원 서비스 API 단위 테스트 

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-member#17]
## **✏️ Feature 작업**
회원 서비스 단위 테스트

## **✅ TO-DO** 
- [x] Repository 단위 테스트 - DataJpaTest
- [x] Service Layer 단위 테스트 
- [x] Controller 단위 테스트

## **🚨 주의사항** 
✔️ 없음
