### ISSUE TITLE
[BE] OTT 서비스 API 테스트 코드 작성 및 단위 테스트

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-member#24]
## **✏️ Feature 작업**
OTT 서비스 단위 테스트 작성

## **✅ TO-DO** 
- [x] Web Layer (Controller)
- [x] Service Layer (Service)
- [x] Persistent Layer (Repository)

## **🚨 주의사항** 
✔️
