### ISSUE TITLE
[BE]  회원 서비스 Jenkins 연동 및 Develop 브랜치 PR시 자동 배포 확인 테스트

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-member#3]
## **✏️ Feature 작업**
회원 서비스 프로젝트에 젠킨스 연동을 통해 Develop 브랜치에 PR되고 Deploy Label이 지정되는 경우 클라우드 서버에 자동 배포가 되는지 확인한다.

## **✅ TO-DO** 
- [ ] Jenkins 서버 구축 및 파이프라인 설정
- [ ] Member 프로젝트에 PR 하기 위해 간단한 테스트 코드 작성 후 Develop Merge 테스트
- [ ] Deploy 라벨을 PR 시 지정

## **🚨 주의사항 및 기타사항** 
✔️ 모든 연동 확인 후 PR 테스트 진행
