### ISSUE TITLE
[BE] Common Response Success 리팩토링 (회원, 포인트, 관심 OTT, OTT서비스)

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-member#40]
## **✏️ Feature 작업**
회원 , 포인트, 관심 OTT, OTT 서비스 ResponseEntity 포맷 수정

## **✅ TO-DO** 
- [x] 회원 , 포인트, 관심 OTT, OTT 서비스 ResponseEntity 포맷 수정
- [x] 회원 서비스 로그인 및  JWT 토큰 파싱 부분 수정
- [x] 소셜 로그인 인증서버로 로직 구분으로 인한 로직 삭제
- [x] 소셜 로그인 및 회원 가입 로직 테스트 코드 삭제

## **🚨 주의사항** 
✔️  테스트 시 Eureka Server -> API Gateway -> API 서버순 로딩
