### ISSUE TITLE
[BE] 회원 서비스 API 구현

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-member#9]
## **✏️ Feature 작업**
회원 서비스 API 구현

## **✅ TO-DO** 
- [x] 사용자 정보 입력
- [x] 추천인 아이디 조회
- [x] 로그 아웃
- [x] 닉네임 중복 확인 및 닉네임 검색
- [x] 등급 및 포인트 조회, 변동 사항 
- [x] 프로필 보기 , 프로필 수정 

## **🚨 주의사항 및 기타사항** 
✔️ 회원 서비스 API 구현 및 테스트 코드 작성
